### ISSUE TITLE
BREAKING/BUG: $LG3_HOME/lg3.conf prevents env vars to be set in run scripts

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#128]
In the develop branch, `$LG3_HOME/lg3.conf` has been [updated](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/commit/5a576c0ca7af11f1a818f8df23c7f116e2aea3ec) such that it sets variables like:
```sh
CONV=${LG3_HOME:?}/patient_ID_conversions.tsv
```

This means that when, say, `runs_demo/_run_Pindel`, tries to set this variable to:
```r
CONV=${CONV:-patient_ID_conversions.tsv}
```
it already set.  This means that it will _not_ pick up `./patient_ID_conversions.tsv` in the users working directory (=project folder) but the hard-coded one that comes with the pipeline.

This was caught when I was trying to run check the pipeline:
```sh
$ more _Pindel_Patient157t10.out
[...]
Input:
- PATIENT=Patient157t10
- PROJECT=LG3
- CONV=/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel/patient_ID_conversions.tsv
ERROR: No such file: '/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel/patient_ID_conversions.tsv' (working directory '/cbc2/data2/henrik/re
positories/UCSF-CostelloLab/test-devel-20190419-t10-pindel_0.2.5b8')
Traceback:
1: assert_file_exists() on line #157 in /cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel/scripts/utils.sh
2: main() on line #57 in /var/spool/torque/mom_priv/jobs/1334861.cclc01.som.ucsf.edu.SC
Exiting (exit 1)
```

**Comment by HenrikBengtsson** [comment]
@ivan108, I'm assigning this one along to you, especially since you've made those changes since the last release.  Make sure to update so that Protection #129 is applied - that will help robustifying the development.

**Comment by ivan108** [comment]
Yes, it is a bug, good catch!

The correct line in `$LG3_HOME/lg3.conf` should read:

`CONV=patient_ID_conversions.tsv`

Will do some more tests...

I also propose that we never pass the same parameter by lg3.conf files AND environment. Only runtime parameters which change with every run should be passed by environment, e.g. PATIENT.. 

PS: I am fine with working outside of $LG3_HOME, in that way I will have the same experience as other LG3 users.

**Comment by HenrikBengtsson** [comment]
> I also propose that we never pass the same parameter by lg3.conf files AND environment. 

I agree consistency is useful, but we cannot remove support for env vars until `lg3.conf` is fully implemented, e.g. Issue #127.  Until then, `lg3.conf` should not set those if already set (as env var).  Better to make small, conservative, backward compatible changes and then slowly deprecate support for old ways of calling the pipeline.  You don't want to mess up end users existing script from one release to the other.

**Comment by HenrikBengtsson** [comment]
@ivan108, have you had a chance to fix/undo this?

**Comment by ivan108** [comment]
I fixed lg3.conf file in current develop branch.

Meanwhile, I am working on refactoring the code to use lg3.conf files in all steps of the pipeline.
I don't like hybrid setup when the same parameter sometimes is taken from config file and sometimes not. It is confusing, so I am not making intermediate commits, but do a lot of testing at every step. Then I will commit it all at once. In that case it would be easy to roll back if we don't like it..

**Comment by HenrikBengtsson** [comment]
Setting
```sh
CONV=patient_ID_conversions.tsv
```
in `lg3.conf` won't solve it either. As it stands now, we cannot really set it at all, because it prevents the user from setting env var `CONV` outside.  This is because in the scripts etc we use:
```sh
source_lg3_conf   ## <= here CONV is set regardless what the use sets outside ...
[...]
CONV=${CONV:-patient_ID_conversions.tsv}   ## <= ... so, this will do nothing
```

To fix this, anything that should be allowed to be set via env vars needs to be set conditionally in the `lg3.conf` file, e.g.
```s
CONV=${CONV:-patient_ID_conversions.tsv}
```
This won't override `CONV` is already set.

**Comment by HenrikBengtsson** [comment]
> Meanwhile, I am working on refactoring the code to use lg3.conf files in all steps of the pipeline.

FYI, the best/safest way to do this, is to work in a separate Git branch, e.g.
```sh
$ git checkout develop
$ git checkout -b feature/lg3.conf
```
and do your commits to that new 'feature/lg3.conf' branch without risking messing up the 'develop' branch.  You can even push it to GitHub.  When you're happy with 'feature/lg3.conf' and it's been _well tested_, we can do:
```sh
$ git checkout develop
$ git merge feature/lg3.conf
```
to bring it all into the 'develop' branch.  Then run another round of testing before releasing (to 'master' branch)

**Comment by ivan108** [comment]
To continue discussion about best way to setup config files:

Your suggestion with conditional assignment like `CONV=${CONV:-patient_ID_conversions.tsv} `
indeed will give us extra flexibility to overwrite config settings by env var. But does user always need such flexibility? CONV parameter is a good example when such flexibility is not needed, because you don't change it from run to run, in fact you don't need to change it at all until next project. Same is applicable to the most of other parameters.

I also see  potential confusion for the users, let's say user edited local config file with different $CONV value he wants for the next runs,  but there is still env var $CONV set in the previous run, which will supersede the value in config file  .  So, the user would start the run with the wrong conversion file!

Suggestion 1: Some variables which change often, like $PATIENT, should never be included in config files.

Suggestion 2: All parameters pointing to files or directories in config files should always have absolute path. In that case we don't need to worry readlink'ing them

Suggestion 3: All parameters in both config files should be exported, e.g.
`export GATK4="${LG3_HOME}/tools/gatk-4.1.1.0/gatk"`
 In that case we only need to source config files twice: in launching scripts `_run_* `and PBS scripts `*.pbs `, but not in numerous downstream shell scripts `*.sh`. Also much less variables would need to be passed to shell scripts, because they are already in the environment ...

Suggestion 4: local lg3.conf file should be renamed to something else (lg3_user.conf?) and be part of repo with instructions and some initial parameters which are likely to be changed, commented out. 
During pipeline installation the lg3_user.conf should be somehow copied to the user working directory.
May using `lg3 test setup` ??

What do you think? Thx!

**Comment by HenrikBengtsson** [comment]
@ivan108, can I take a stab at fixing this?  I'll try to do a minimal fix - I hope I can do it with messing too much with your plans on lg3.conf.

@shuntsman-ucsf and @eladziv are ready & pretty keen to process their data with Pindel2.

**Comment by ivan108** [comment]
Yes, go ahead with the fix, thanks!

I slowed down testing lg3.conf branch (origin/feature/lg3.conf), which already looks good, because I am in the middle of processing a large exome batch...

**Comment by HenrikBengtsson** [comment]
Fixed.
