### ISSUE TITLE
extra code in shell scripts?

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#19]
A quick question, in most shell scripts we have the following lines:
```
#$ -clear
#$ -S /bin/bash
#$ -cwd
#$ -j y
```

What does it do and do we need it??

**Comment by HenrikBengtsson** [comment]
They look like SGE scheduler markup (rather than PBS markup).  They might be remnants from legacy times.  I think they can go, but let's hold back wiping them / doing any major edits in develop because I've done lots in feature/envvars and it'll be probably tricky to merge.   Let's target this for "next next release" (I've flagged this issue with that milestone).

**Comment by HenrikBengtsson** [comment]
Dropped.

**Comment by ivan108** [comment]
Oops, I also updated scripts/Merge.sh, now we have a conflict. How do we merge?

**Comment by ivan108** [comment]
Not sure which file are you talking about?

**Comment by HenrikBengtsson** [comment]
You said you updated `scripts/Merge.sh` and then got a merge conflict, that means `git merge` should complain about that one, and that's the one that needs to be fixed.

**Comment by ivan108** [comment]
I see... I have never used "git merge"..
